Added service for subscriptions
Tingaev/pet-project-connections pull request #1
Opened 2023-07-08 18:00 UTC by Tingaev

2023-07-08 18:14 UTC, Tingaev commented on internal/services/service_test.go
> +    callArgsForAnotherMethods map[int]CallArgs  // TODO: rename this
По сути у меня на два метода одна сигнатура, на два других другая. Не уверен, что так делать лучшая идея.

2023-07-08 18:15 UTC, Tingaev commented on internal/services/service_test.go
> +    }
Конкретно if`ы на проверку много где повторяются, вполне логичным мне кажется будет позже сделать из них что-то типа вспомогательных функций, дабы не повторять это по сто раз

2023-07-08 18:17 UTC, Tingaev commented on internal/services/service.go
> +	SubscriptionStorage // TODO: когда появятся отличия в их интерфейсе, тогда нужно будет это убрать
Очень спорный момент, пока решил так оставить. Просто в моем кейсе получается так, что интерфейс сервиса схож с интерфейсом, который предназначен для хранения.

2023-07-08 18:19 UTC, Tingaev commented on internal/services/service.go
> +	GetSubscriptions(id uuid.UUID, offset int, limit int) ([]uuid.UUID, error)
Вероятнее всего в последующем в сигнатуры добавиться контекст

2023-07-08 18:20 UTC, Tingaev commented on internal/services/service_test.go
> +type CallArgs struct {
Помойное название, в структуре Мока лежит поле с таким названием

2023-07-08 18:22 UTC, Tingaev commented on internal/services/service_test.go
> +func TestGetSubscribers(t *testing.T) {
Пока проверяется только один позитивный кейс, в последующем планирую добавить маппинг ошибок из Storage`а в ошибки Service`а и тогда уже и кейс добавится соответственно

2023-07-08 18:24 UTC, Tingaev commented on internal/services/service_test.go
> +    }
И по поводу юзания reflect для такой проверки. Ок/не ок?

2023-07-09 09:43 UTC, artemy-ant requested changes
по поводу структуры директори, папка internal сама собой уже подразумевает деление на отдельные внутренние сервисы, нет нужды создавать отедльные под папку с сервисами. каждый отдельный сервис - отдельный модуль со своим названием. Сейчас у тебя вырисовывается уже некоторый internal/postgres/subscription_repository.go и некий сервис SubscriptionsService который будет содержать что-то более абстрактное, хз как его пока назвать, типо internal/subscription/service.go

2023-07-09 09:43 UTC, artemy-ant commented on go.mod
> +go 1.19
уже есть более новая версия 1.20+

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service.go
> +	GetSubscriptions(id uuid.UUID, offset int, limit int) ([]uuid.UUID, error)
да, он точно нужен, прокинь его лучше сразу. А если у тебя уже есть вызовы этих методов, а контекста еще нет, можешь ставить заглушку на время - context.ToDo()

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service.go
> +type SubscriptionStorage interface {
это стоит вынести в отдельную директорию внутри internal, например interna/postgres/subscription_repository.go

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service.go
> +type Service struct {
наружу у тебя должен везде торчать твой интерфейс сервиса, а не сама структура сервиса, поэтому ее с маленькой буквы делаем и добавляем доп. метод:
```go
func NewService() SubscriptionsService {
    return &service{}
}
```
здесь же через этот инициализатор будем прокидывать зависимости, например subscription_repository

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service.go
> +func createService(s SubscriptionStorage) Service {
Это заменится на `func NewService() SubscriptionsService`

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service.go
> +func (s *Service) HealthCheck() error {
Этот метод позже добавится через echo отдельным роутером, здесь не его место

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service_test.go
> +    callArgsForAnotherMethods map[int]CallArgs  // TODO: rename this
лучше использовать github.com/stretchr/testify/mock, с ним получится так:
```go
type SubscriptionStorageMock struct {
    mock.Mock
}

func (m *SubscriptionStorageMock) CreateSubscription(subscriberId uuid.UUID, targetId uuid.UUID) error {
    args := m.Called(subscriberId, targetId)
    return args.Error(1)
}

func (m *SubscriptionStorageMock) GetSubscribers(id uuid.UUID, offset int, limit int) ([]uuid.UUID, error) {
    args := m.Called(id, offset, limit)
    return args.Get(0).([]uuid.UUID), args.Error(1)
}

<...>
```

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service_test.go
> +type MockSubscriptionStorage struct {
моки лучше держать отдельно, например вынести в отдельную папку в корне - test/mocks/subscription_storage.go

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service_test.go
> +	// Assert
пакет github.com/stretchr/testify/require и github.com/stretchr/testify/asset, и делай проверки без if:
```go
assert.NotNil(t, result)

assert.Equal(t, storage.countCall, 1)
```

2023-07-09 09:43 UTC, artemy-ant commented on internal/services/service_test.go
> +    }
отписал выше

2023-07-09 10:29 UTC, Tingaev commented on internal/services/service.go
> +type SubscriptionStorage interface {
Просто видишь хочется его оставить в каком-то месте, чтобы он не был привязан к конкретному хранилищу, а так мы привяжемся к постгресу.

2023-07-09 10:29 UTC, Tingaev commented on internal/services/service.go
> +type Service struct {
Согласен, переделаю

2023-07-09 10:30 UTC, Tingaev commented on internal/services/service.go
> +func (s *Service) HealthCheck() error {
Согласен

2023-07-13 16:48 UTC, Tingaev commented on internal/services/service_test.go
> +    callArgsForAnotherMethods map[int]CallArgs  // TODO: rename this
Такс, это добавил

2023-07-13 16:49 UTC, Tingaev commented on internal/services/service_test.go
> +    }
Такс, это добавил

2023-07-13 16:49 UTC, Tingaev commented on internal/services/service.go
> +	GetSubscriptions(id uuid.UUID, offset int, limit int) ([]uuid.UUID, error)
Такс, это добавил

2023-07-13 16:51 UTC, Tingaev commented on internal/services/service.go
> +func (s *Service) HealthCheck() error {
Выпилил

2023-07-13 16:52 UTC, Tingaev commented on internal/services/service_test.go
> +	// Assert
Такс, это заюзал

2023-07-14 10:58 UTC, Tingaev commented on internal/services/service_test.go
> +type MockSubscriptionStorage struct {
Вынес

2023-07-14 10:58 UTC, Tingaev commented on go.mod
> +go 1.19
Чуть позже поменяю

2023-07-14 10:59 UTC, Tingaev commented on internal/services/service.go
> +type Service struct {
Переделал

2023-07-14 10:59 UTC, Tingaev commented on internal/services/service.go
> +func createService(s SubscriptionStorage) Service {
Заменил

2023-07-14 11:10 UTC, Tingaev commented on internal/subscription/service_test.go
> +	m "github.com/tingaev/pet-project-connections/test/mocks"
Не уверен, что это лучшее решение. может подумать над названием в целом, если понятно не будет

2023-07-19 10:11 UTC, artemy-ant commented on internal/storage/storage.go
> +type SubscriptionStorage interface {
нейминг нужно чуть подшаманить - при вызове у тебя получится вот так: storage.SubscriptionStorage, Storage из названия интерфейса можно убрать

2023-07-19 10:11 UTC, artemy-ant commented on internal/storage/storage.go
> +	DeleteSubscription(ctx context.Context, subscriberId uuid.UUID, targetId uuid.UUID) error
тут тоже можно убрать Subscription из названия

2023-07-19 10:11 UTC, artemy-ant commented on internal/subscription/service.go
> +type SubscriptionsService interface {
Аналогично убрать Service из названия, про нейминг можно тут почитать https://go.dev/doc/effective_go#names

2023-07-19 10:11 UTC, artemy-ant commented on internal/subscription/service.go
> +func CreateService(s storage.SubscriptionStorage) service {
Инициализатор начинается с New

2023-07-19 10:11 UTC, artemy-ant commented on internal/subscription/service_test.go
> +	// Arrange
отступ

2023-07-30 19:40 UTC, merged